direction: right


Stance: {
    Swing{
        heap {
            style: {
                font-color: red
            }
        }
        heap -> knee : "thigh"
        knee -> ankle : "shank"
        ankle -> foot : "foot"
        foot {
            style: {
                font-color : blue
            }
        }
    }

    MidStance/HeelStrike{
        ankle {
            style: {
                font-color: red
            }
        }
        ankle -> knee : "shank" 
        knee -> heap : "thigh"
        heap -> torso : "torso"

        torso {
            style: {
                font-color : blue
            }
        }
    }

    Toe-off{
        toe {
            style: {
                font-color: red
            }
        }
        toe -> ankle : "foot"
        ankle -> knee : "shank"
        knee -> heap : "thigh"
        heap -> torso : "torso"

        torso {
            style: {
                font-color : blue
            }
        }
        
    }
}

# Stance with UpperBody: {
#     Swing 
#     Mid-Stance / Heel-Strike 
#     Toe-off

# }

# Stance -> Stance with UpperBody : "UpperBody is attached"








# direction: right

# Struct: {
 

#   Back: {
#     shape: class

#     - roll: double
#   }

#   BodySensor: {
#     shape: class

#     - legL: Leg
#     - legR: Leg
#     - back: Back

#     +GetSensor(void): BODY_SENSOR*
#   }
#   BOS: {
#     shape: class

#     - left: double
#     - right: double

#     +calculate_BOS(BOS*): void
#   }
#   Leg -> BodySensor: {
#     # style: {
#     #   stroke-width: 5
#     # }
#   }

#   Back -> BodySensor: {
#     # style: {
#       # stroke-width: 5
#     # }
#   }
# }




# Function:{

#   BodySensor* GetSensor(void): {
#     shape: class
  
#     - sensor: BodySensor
#     - pBodySensor: BodySensor*
#   }

#   void calculate_BOS(BOS*): {
#     shape: class

#     - THIGH_LENGTH: const double
#     - SHANCK_LENGTH: const double

#     - hip_angle_left: double
#     - hip_angle_right: double

#     - knee_angle_left: double
#     - knee_angle_right: double

#     - leg_length_left: double
#     - leg_length_right: double

#     - leg_hip_angle_left: double
#     - leg_hip_angle_right: double

#     - leg_angle_left: double
#     - leg_angle_right: double

#     -DEG2RAD: const double
#     -RAD2DEG: const double

#     +GetSensor(void): BODY_SENSOR*
#   }

#   void calculate_COM(double*): {
#     shape: class

#     - Lx3: const double
#     - Ly3: const double

#     - torso_angle: double

#     -DEG2RAD: const double
#     -RAD2DEG: const double

#     +GetSensor(void): BODY_SENSOR*
#   }
#   bool check_stability(BOS *, double*):{
    
#     shape: class

#     -is_stable : bool

#     +calculate_BOS(BOS*) : void
#     +calculate_COM(double*) : void
#   }
#   BodySensor* GetSensor(void)-> void calculate_BOS(BOS*)
#   BodySensor* GetSensor(void)-> void calculate_COM(double*)

#   void calculate_BOS(BOS*)->bool check_stability(BOS *, double*){

#   }
#   void calculate_COM(double*)->bool check_stability(BOS *, double*)

# }